// Mocks generated by Mockito 5.4.6 from annotations
// in handwerker_app/test/unit/order_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:handwerker_app/data/services/api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i4.Future<_i2.Response<dynamic>> sendOtp(String? phone) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtp,
          [phone],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #sendOtp,
            [phone],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> verifyOtp(
    String? phone,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [
            phone,
            code,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #verifyOtp,
            [
              phone,
              code,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> refreshToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [token],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #refreshToken,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<void> logout(String? refreshToken) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [refreshToken],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordConsent({
    required bool? terms,
    required bool? privacy,
    required bool? dataProcessing,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordConsent,
          [],
          {
            #terms: terms,
            #privacy: privacy,
            #dataProcessing: dataProcessing,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Response<dynamic>> getCustomerProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCustomerProfile,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getCustomerProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> updateCustomerProfile(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomerProfile,
          [data],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #updateCustomerProfile,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<void> deleteCustomerAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteCustomerAccount,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Response<dynamic>> getCraftsmanProfile(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCraftsmanProfile,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getCraftsmanProfile,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> updateAvailability(bool? isOnline) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAvailability,
          [isOnline],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #updateAvailability,
            [isOnline],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<void> updateLocation(
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [
            lat,
            lng,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Response<dynamic>> getWallet() => (super.noSuchMethod(
        Invocation.method(
          #getWallet,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getWallet,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getServiceCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getServiceCategories,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getServiceCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> createOrder(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [data],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #createOrder,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> listOrders({
    String? status,
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrders,
          [],
          {
            #status: status,
            #page: page,
            #size: size,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #listOrders,
            [],
            {
              #status: status,
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getOrder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOrder,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getOrder,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> markOnTheWay(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markOnTheWay,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #markOnTheWay,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> confirmArrival(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmArrival,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #confirmArrival,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> startJob(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #startJob,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #startJob,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> requestPriceRevision(
    String? orderId,
    double? newPrice,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPriceRevision,
          [
            orderId,
            newPrice,
            reason,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #requestPriceRevision,
            [
              orderId,
              newPrice,
              reason,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> acceptPriceRevision(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptPriceRevision,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #acceptPriceRevision,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> completeOrder(
    String? orderId,
    double? finalPrice,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeOrder,
          [
            orderId,
            finalPrice,
            notes,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #completeOrder,
            [
              orderId,
              finalPrice,
              notes,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> customerConfirmOrder(
    String? orderId,
    int? rating,
    String? review,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #customerConfirmOrder,
          [
            orderId,
            rating,
            review,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #customerConfirmOrder,
            [
              orderId,
              rating,
              review,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> cancelOrder(
    String? orderId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [
            orderId,
            reason,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #cancelOrder,
            [
              orderId,
              reason,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> listProposals(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listProposals,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #listProposals,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> submitProposal(
    String? orderId, {
    required double? price,
    required int? etaMinutes,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitProposal,
          [orderId],
          {
            #price: price,
            #etaMinutes: etaMinutes,
            #comment: comment,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #submitProposal,
            [orderId],
            {
              #price: price,
              #etaMinutes: etaMinutes,
              #comment: comment,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> acceptProposal(
    String? orderId,
    String? proposalId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptProposal,
          [
            orderId,
            proposalId,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #acceptProposal,
            [
              orderId,
              proposalId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getPayment(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPayment,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getPayment,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> listPayouts({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listPayouts,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #listPayouts,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> requestPayout(double? amount) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPayout,
          [amount],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #requestPayout,
            [amount],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> submitRating(
    String? orderId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitRating,
          [
            orderId,
            data,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #submitRating,
            [
              orderId,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> openDispute(
    String? orderId,
    String? description, {
    List<String>? mediaUrls,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openDispute,
          [
            orderId,
            description,
          ],
          {#mediaUrls: mediaUrls},
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #openDispute,
            [
              orderId,
              description,
            ],
            {#mediaUrls: mediaUrls},
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getDispute(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDispute,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getDispute,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> listMessages(
    String? orderId, {
    int? page = 0,
    int? size = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listMessages,
          [orderId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #listMessages,
            [orderId],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> sendMessage(
    String? orderId, {
    String? text,
    String? mediaUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [orderId],
          {
            #text: text,
            #mediaUrl: mediaUrl,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #sendMessage,
            [orderId],
            {
              #text: text,
              #mediaUrl: mediaUrl,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> listNotifications({
    bool? unreadOnly = false,
    int? page = 0,
    int? size = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listNotifications,
          [],
          {
            #unreadOnly: unreadOnly,
            #page: page,
            #size: size,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #listNotifications,
            [],
            {
              #unreadOnly: unreadOnly,
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<void> markNotificationRead(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markNotificationRead,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAllNotificationsRead() => (super.noSuchMethod(
        Invocation.method(
          #markAllNotificationsRead,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
